### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by simonnarang** [Yelp/yelp-ios#38] opened 2016-06-27 14:23 UTC
Is there a version of this for Swift 3.0?

**Comment by SSheldon** [comment] 2016-06-27 17:11
Hey @simonnarang, this library doesn't contain any Swift (it's pure Objective-C). What issues are you running into when trying to use it with Swift 3?

**Comment by simonnarang** [comment] 2016-06-27 17:25
Nothing I was just looking around for a swift 3 yelp API because I am currently having trouble with generating a signature... I'm pretty sure I am generating it properly but the yelp API responds saying that the signature is invalid and the base string should begin with `GET\\` not `GET&`(correct oauth percent encoding) which is very confusing.
Thanks

**Comment by simonnarang** [comment] 2016-06-27 17:26
@SSheldon I saw you are part of yelp so do you know anything about this error^?
Thanks again

**Comment by SSheldon** [comment] 2016-06-27 19:01
@simonnarang, hmm no I'm not sure what would be causing that. You should give this library a shot! It'll do the signing for you and if you run into any issues it'll be a lot easier for us to help. Here's an example of using this library from Swift: https://github.com/Yelp/yelp-api/blob/master/v2/swift/main.swift

If you're using CocoaPods it should be easy to integrate, just add `YelpAPI ~> 1.0` to your podfile.

**Comment by simonnarang** [comment] 2016-06-27 19:36
@SSheldon can yelp-api integrate with swift package manager?

**Comment by simonnarang** [comment] 2016-06-27 19:41
And wow that main.swift file is so much simpler than what I currently have

**Comment by simonnarang** [comment] 2016-06-27 19:51
Carthage would also work just can't use cocoapods😅

**Comment by SSheldon** [comment] 2016-06-27 20:08
We can add Carthage support! I've opened #39 to tackle that.

From what I've seen it shouldn't be too hard for us to support Carthage, but we don't use Carthage here at Yelp, so any advice or suggestions are welcome 😊

**Comment by simonnarang** [comment] 2016-06-27 22:16
Around when do you think support will be added?

**Comment by SSheldon** [comment] 2016-06-29 02:02
@simonnarang, I was hoping we could add Carthage support quickly but there are more obstacles than I expected, detailed in #39 :(

Can I recommend [cocoapods-rome](https://github.com/neonichu/Rome) to you? I just tested it out and it's working for me! Basically, somewhere you'll just create a podfile like this:
``` ruby
platform :ios, '8.0'

plugin 'cocoapods-rome'

target 'MyApp' do
  pod 'YelpAPI'
end
```

Then install the gems for `cocoapods` and `cocoapods-rome`, run `pod install`, and copy the produced Frameworks. You can copy those frameworks into your project and there'll be no trace at all of cocoapods in your project, it'll look just like they had been built by Carthage.

**Comment by SSheldon** [comment] 2016-11-23 01:48
Closing out as a duplicate of #39 for adding Carthage support. Fingers crossed though that cocoapods-rome worked out for you!

**Closed by SSheldon** 2016-11-23 01:48 UTC
